#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=humann3_rerunMoreTime
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --cpus-per-task=6
#SBATCH --mem-per-cpu=10g
#SBATCH --time=100:00:00
#SBATCH --account=bfoxman1
#SBATCH --partition=standard
#SBATCH --output=/scratch/bfoxman_root/bfoxman/blostein/meta_CAVITIES/Humann2/Code/%x-%j.log


#wget the databases and install them https://forum.biobakery.org/t/difficulty-downloading-databases-in-humann3/1343
# http://cmprod1.cibio.unitn.it/databases/HUMAnN/

source activate biobakery3
cd /scratch/bfoxman_root/bfoxman/blostein/meta_CAVITIES/Humann2/Files

export http_proxy=http://proxy.arc-ts.umich.edu:3128/
export FTP_PROXY=http://proxy.arc-ts.umich.edu:3128/
export ftp_proxy=http://proxy.arc-ts.umich.edu:3128/
export HTTPS_PROXY=http://proxy.arc-ts.umich.edu:3128/
export https_proxy=http://proxy.arc-ts.umich.edu:3128/
export HTTP_PROXY=http://proxy.arc-ts.umich.edu:3128/


for f in *.fastq; do humann -i $f -o humann3_output --resume \ 
    --nucleotide-database  /scratch/bfoxman_root/bfoxman/blostein/humann3_db/chocophlan/ \ 
    --protein-database /scratch/bfoxman_root/bfoxman/blostein/humann3_db/uniref/ \
    -v --threads 4 \
    --metaphlan-options="-x  /home/blostein/metaphlan_db/mpa_v30_CHOCOPhlAn_201901"; done

#how to run with specific files instead of all the .fastq files in the directory 
#files=( Sample_72_cat.fastq Sample_73_cat.fastq Sample_77_cat.fastq Sample_83_cat.fastq)
#for f in "${files[@]}"; do humann -i $f -o humann3_output --resume --nucleotide-database  /scratch/bfoxman_root/bfoxman/blostein/humann3_db/chocophlan/ --protein-database /scratch/bfoxman_root/bfoxman/blostein/humann3_db/uniref/ -v --threads 6 --metaphlan-options="-x  /home/blostein/metaphlan_db/mpa_v30_CHOCOPhlAn_201901"; done
